### ISSUE TITLE
not returning the $empty state

### ISSUE THREAD

**Issue by iamzjohn** [Emerjoin/Hi-List#10]
The Hi-List isn't returning the $empty when receives a empty row data, and zeroes in total rows also total Pages, it gives a Arithmetic exception,

The view code: 
```html
<!-- Main content 24-->
<div class="content-wrapper members-list-container" style="display: none;">
    <list name="membersList" each="m" src="MembersFrontier.fetch" repeat-element=".member-row" preFetch="preListFecth(filter)" postFetch="postListFecth(result)" per-page="24">

    <div class="row">

        <div class="col-lg-3 col-md-6 member-row">
            <div class="thumbnail no-padding" style="min-height: 315px;">
                <div class="thumb">
                    <img aload="webroot/assets/images/loading.gif" asrc="{{m.imageUrl}}" err="webroot/assets/images/member.png" style="border-radius:none;" alt="">
                    <div class="caption-overflow">
                        <span>
                            <a ng-click="viewProfile(m.username)" class=" btn-icon btn-xs"><i style="color: #f4e842;" class="icon-enter3"></i></a>
                        </span>
                    </div>
                </div>

                <div class="caption text-center" >
                    <h6 class="text-semibold no-margin" >{{m.name}} <small class="display-block" style=" height: 20px; text-overflow: ellipsis-word; ">{{m.title}}</small></h6>
                    <br/>
                    <span class="label bg-grey-300">{{m.city.name}}</span>
                </div>
            </div>
        </div>

    </div>
    <div class="row" ng-show="$empty">
        <center>
            <br/>
            <h1 style="font-size: 100px; font-weight: bold;">:(</h1>
            <h1>A pesquisa não retornou nenhum membro!</h1>
            <h5><em>trocar por foto nice</em></h5>
            <br/>
        </center>
    </div> 
    </list>
</div>
```
 
The Frontier code: 
```java
@Inject
    private MemberService memberService;
    
    public Map fetch(int pageNumber, int itemsPerPage, Map filter, Map ordering) throws Exception{
            
          Map listData = memberService.fetch(pageNumber, itemsPerPage, filter, ordering);
          
          List<Member> rows = (List<Member>) listData.get("rows");//Its empty here
          int totalMachedRows = (int) listData.get("count");//The value is zero
          int totalMatchedPages = (int) listData.get("totalPages");//The value is zero
          
          return HiList.listEncode(rows, totalMachedRows, pageNumber, totalMatchedPages);
                
    }
```

I have a log here: 

```java

Info:   11:17:16.166 [http-listener-1(2)] ERROR o.e.hi.web.req.FrontiersReqHandler - An error occurred during frontier method invocation <MembersFrontier.fetch>
java.lang.ArithmeticException: / by zero
	at org.emerjoin.hi.web.component.HiList.pages(HiList.java:22) ~[HiList-2.0.0.jar:na]
	at org.emerjoin.hi.web.component.HiList.listEncode(HiList.java:52) ~[HiList-2.0.0.jar:na]
	at org.emerjoin.hi.web.component.HiList.listEncode(HiList.java:39) ~[HiList-2.0.0.jar:na]
	at frontiers.MembersFrontier.fetch(MembersFrontier.java:36) ~[MembersFrontier.class:na]
	at frontiers.MembersFrontier$Proxy$_$$_WeldClientProxy.fetch(Unknown Source) ~[MembersFrontier.class:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.emerjoin.hi.web.frontier.FrontierInvoker.invoke(FrontierInvoker.java:54) ~[Hi-Framework-1.1.0.jar:na]
	at org.emerjoin.hi.web.req.FrontiersReqHandler.executeFrontier(FrontiersReqHandler.java:279) ~[Hi-Framework-1.1.0.jar:na]
	at org.emerjoin.hi.web.req.FrontiersReqHandler.handle(FrontiersReqHandler.java:430) ~[Hi-Framework-1.1.0.jar:na]
	at org.emerjoin.hi.web.req.FrontiersReqHandler$Proxy$_$$_WeldClientProxy.handle(Unknown Source) [Hi-Framework-1.1.0.jar:na]
	at org.emerjoin.hi.web.internal.Router.doRoute(Router.java:113) [Hi-Framework-1.1.0.jar:na]
	at org.emerjoin.hi.web.internal.Router$Proxy$_$$_WeldClientProxy.doRoute(Unknown Source) [Hi-Framework-1.1.0.jar:na]
	at org.emerjoin.hi.web.DispatcherServlet.doHandle(DispatcherServlet.java:82) [Hi-Framework-1.1.0.jar:na]
	at org.emerjoin.hi.web.DispatcherServlet.doPost(DispatcherServlet.java:109) [Hi-Framework-1.1.0.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api.jar:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api.jar:3.1.0]
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682) [web-core.jar:na]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318) [web-core.jar:na]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160) [web-core.jar:na]
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734) [web-core.jar:na]
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673) [web-core.jar:na]
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99) [web-glue.jar:na]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174) [web-core.jar:na]
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416) [web-core.jar:na]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283) [web-core.jar:na]
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459) [kernel.jar:na]
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167) [kernel.jar:na]
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206) [nucleus-grizzly-all.jar:na]
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180) [nucleus-grizzly-all.jar:na]
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235) [nucleus-grizzly-all.jar:na]
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119) [nucleus-grizzly-all.jar:na]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283) [nucleus-grizzly-all.jar:na]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200) [nucleus-grizzly-all.jar:na]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132) [nucleus-grizzly-all.jar:na]
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111) [nucleus-grizzly-all.jar:na]
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77) [nucleus-grizzly-all.jar:na]
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536) [nucleus-grizzly-all.jar:na]
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112) [nucleus-grizzly-all.jar:na]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117) [nucleus-grizzly-all.jar:na]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56) [nucleus-grizzly-all.jar:na]
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137) [nucleus-grizzly-all.jar:na]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591) [nucleus-grizzly-all.jar:na]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571) [nucleus-grizzly-all.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]

```

**Comment by iamzjohn** [comment]
Sorry my day, I was using the older version of Hi List where the params where:

```java
/**
* @param rows is the data
* @param totalMatchedRows is the total number of rows that matches with the criteria or whatever
* @param pageNumber is the number of the page where is actually on the frontEnd
* @param totalMatchedPages is the Number of total Pages that Match with the criteria or whatever
*/
HiList.listEncode(rows, totalMachedRows, pageNumber, totalMatchedPages);
```

but the actual version is different now its: 
```java
/**
* @param rows is the data
* @param totalMatchedRows is the total number of rows that matches with the criteria or whatever
* @param pageNumber is the number of the page where is actually on the frontEnd
* @param itemsPerPage is the Number of items per page
*/
HiList.listEncode(rows, totalMachedRows, pageNumber, itemsPerPage);
```
